[package]
name = "price-check"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.18", default-features = false, features = ["rustls-tls", "brotli"] }
scraper = { version = "0.17.1", default-features = false, features = ["errors"] }
tokio = { version = "1.29.1", default-features = false, features = ["rt", "macros"] }
